version: 0.0
os: linux

### files 섹션: 배포 파일에 대한 설정
files:
  - source:  /   # 인스턴스에 복사할 디렉토리 경로
    destination: /home/ubuntu/app  # 인스턴스에서 파일이 복사되는 위치
    overwrite: yes  # 복사할 위치에 파일이 있는 경우 대체

### permissions 섹션: 섹션에서 복사한 파일에 대한 권한 설정
permissions:
  - object: /   # 권한이 지정되는 파일 또는 디렉토리
    pattern: "**"  # 매칭되는 패턴에만 권한 부여(optional)
    owner: ubuntu  # object의 소유자(optional)
    group: ubuntu  # object의 그룹 이름(optional)
    mode: 755

### hooks 섹션: 배포 이후에 수행할 스크립트
hooks:
#  AfterInstall:
#    - location: scripts/stop.sh  # hooks에서 실행할 스크립트 위치
#      timeout: 60  # 스크립트 실행에 허용되는 최대시간(optional), 이를 넘는 경우 배포 실패로 간주됨
#      runas: ubuntu  # 스크립트를 실행하는 사용자(optional)
  AfterInstall:
    - location: deploy.sh
      timeout: 60   # 60 안에 실행하지 못하면 배포 실패로 간주
      runas: root
#  ValidateService:
#    - location: scripts/server-check.sh
#      timeout: 60
