server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  datasource:
    url: jdbc:mysql://simya-db.cxudcrcc5ksr.ap-northeast-2.rds.amazonaws.com:3306/LATENIGHT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: simya
    password: simya1234!!

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB



  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true   # SQL문을 가독성 있게 표현
        show_sql: true  # Hibernate 가 실행한 모든 SQL 문 콘솔로 출력
    #        globally_quoted_identifiers: true
    #        use_sql_comments: true   # 디버깅 정보 출력
    defer-datasource-initialization: true

    security:

      oauth2:
        client:
          registration:
            kakao:
              client-id: 4ab7b193bdd041a30446ede285a1f77a
              client-secret: cjW924pToyagFaxJhQy5Ad3KKFpeEtrU
              redirect-uri: http://localhost:8080/api/authorization_code
              authorization-grant-type: authorization_code
              client-authentication-method: GET
              client-name: kakao
              scope:
                - profile_nickname
                - profile_image
                - account_email
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftl

  profiles:
    active: local

  redis:
    host: localhost
    port: 6379


logging:
  level:
    com.com.backend: DEBUG   # 로깅 레벨 설정
    org.springframework.messaging: TRACE
    org.springframework.web.socket: TRACE


cloud:
  aws:
    credentials:
      access-key: AKIA2SZKNJZQGTBNX5WY
      secret-key: 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
    s3:
      bucket: simya-s3-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  header: Access-Token
  #HS512 알고리즘을 사용 => 512bit(64byte) 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

